# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    alternatives: "puppet/alternatives"
    kmod: "camptocamp/kmod"
    stdlib: "puppetlabs/stdlib"
    ntp: "puppetlabs/ntp"
    auditd: "kemra102/auditd"
    aboe: "aboe/chrony"
    postfix: "camptocamp/postfix"
    logrotate: "puppet/logrotate"
    augeasproviders_shellvar: "herculesteam/augeasproviders_shellvar"
    augeasproviders_pam: "herculesteam/augeasproviders_pam"
    augeasproviders_core:
      repo: "herculesteam/augeasproviders_core"
      ref: "2.1.3"
    augeasproviders_sysctl:
      repo: "herculesteam/augeasproviders_sysctl"
      ref: "2.2.0"
    firewall:
      repo: "puppetlabs/firewall"
      ref: "1.9.0"
